### PR TITLE
Setup an editor config file.

### PR DESCRIPTION
**Pull request by asynts**
This file is picked up by most editors and makes sure that we get the correct indentation and newline on our files.

This would prevent situations like this one: https://github.com/codidact/authentication/pull/9#discussion_r396608380 .

### CODE REVIEW

**Comment by asynts** [comment]
@misha130 Can you try out if Visual Studio still messes with the tab size? Try adding a Nuget package using the user interface and verify that the `.csproj` files are formatted correctly.

**Comment by misha130** [comment]
> @misha130 Can you try out if Visual Studio still messes with the tab size? Try adding a Nuget package using the user interface and verify that the `.csproj` files are formatted correctly.

Works as expected

**Comment by asynts** [comment]
@misha130 Thanks!

**Comment by misha130** [comment]
Can we merge this @luap42?

**Pull request merged**
