### PR TITLE
Add flow for user reset password

### LINKED ISSUE #13: Forgot password Flow
**Is your feature request related to a problem? Please describe.**
From the Login Page there should be an option for forgot password.

**Describe the solution you'd like**
Similar to Login - https://github.com/luap42/codidact-design-draft/blob/master/login.html
Only with Email only.

### PR DESCRIPTION
**Pull request by misha130**
Closes https://github.com/codidact/authentication/issues/13

/account/forgot-password displays a form to enter an email to do a forget password.
On post creates a token and sends it to an email (not implemented)

/account/reset-password?token&email&returnUrl
Displays a form to enter new password and its confirmation.
On posts resets the passwords and moves to the login page.

What is not implemented:
The sending of the email.
How are we supposed to send the email?
Should this be part of the auth project?
How to do the templates?

[Image from Gyazo](https://gyazo.com/f67072601e344eb0a5b91b475404f5ee)

[Image from Gyazo](https://gyazo.com/ee097b56f646cff72538f232bdac6ae4)

[Image from Gyazo](https://gyazo.com/905f8f82c81ced42889b6af0b5e76fa2)

### CODE REVIEW

**Comment by asynts** [comment]
> Should this be part of the auth project?

It has to be. Otherwise, we would have to share the email address with the core application.

**Comment by misha130** [comment]
> > Should this be part of the auth project?
> 
> It has to be. Otherwise, we would have to share the email address with the core application.

I didn't mean it to be in core.
Maybe some sort of outside project that deals with emails and sends them.
I am just concerned about duplicated code that is both in core and auth.
Maybe a message queue that receives a request and sends it?
Maybe an API that that does it?

Maybe I am overthinking the arch

**Comment by cellio** [comment]
If we don't want core to deal with PII, then when core wants to send email (for example, for notifications or subscriptions) it's going to have to send a request to something else to do that.  So either auth provides an email-sending service (since it's got the email addresses already anyway) or there's a third thing, right?  Having auth provide that service seems easier to me, but I'm talking at a high level and don't know what the code implications are.

**Comment by asynts** [comment]
@Daksh14 Wanted to deal with the email stuff. I created #18 for this, there would have to be some coordination to create an interface, `IEmailService` for example, which would be mocked in this pull request and then implemented in #18.

**Comment by misha130** [comment]
> @Daksh14 Wanted to deal with the email stuff. I created #18 for this, there would have to be some coordination to create an interface, `IEmailService` for example, which would be mocked in this pull request and then implemented in #18.

I think something like this:

```
public interface IEmailService{
     Task SendForgotPassword(string email, string name, string token);
}
```

So this email service will have a bunch of methods for each email that could be sent.
Usually I would 100% separate this into an `IEmailService` and a `IAuthenticationMailHandler` where email service would be a builder for emails sending and authentication mail handler would only construct the emails and generate the HTML.

If I could get some feedback before I make any changes that would be great.
@ArtOfCode-  you can input too.

**Comment by misha130** [comment]
Closing this in favor of #19

**Pull request closed without merging**
