### PR TITLE
Load configuration from AWS's parameter store.

### PR DESCRIPTION
**Pull request by asynts**
The most significant change was made in `Program.cs`:

~~~csharp
if (context.HostingEnvironment.IsProduction())
{
    options.AddSystemsManager("/Codidact/Authentication");
}
~~~

This instructs Amazon Web Services (AWS) to read configuration from the parameter store, where secrets will be managed in a production environment.

Since this does exactly what we want without making API calls manually, I removed the `ISecretsService` interface and all implementations.

### CODE REVIEW

**Comment by misha130** [comment]
Well I planned ISecretsService to implement https://aws.amazon.com/secrets-manager/ and in general to be cloud agnostic.
With this you can't run it anymore without AWS

**Comment by asynts** [comment]
> Well I planned `ISecretsService` to implement https://aws.amazon.com/secrets-manager/ and in general to be cloud agnostic.

I did not know that service existed, I have to do more research before I can respond to that.

  > With this you can't run it anymore without AWS.

It would not be possible to run it in production mode, but this is true for the `ISecretsService` thing too. We would check if the environment is production and then inject `AwsSecretsService` for example.

**Comment by misha130** [comment]
> It would not be possible to run it in production mode, but this is true for the ISecretsService thing too. We would check if the environment is production and then inject AwsSecretsService for example.

Well we would add a configuration to the app settings on which type of implementation to use. If the configuration states AWS so AWS. If something else then something else but at least it would give the possibility of switching implementations.

**Comment by asynts** [comment]
> If something else then something else but at least it would give the possibility of switching implementations.

That could be done with the `IConfiguration` stuff too. We'd dynamically add an `IConfigurationSource`.

**Comment by misha130** [comment]
That sounds like a good idea to be honest.
But is it necessary to have a distinction between a secret and a configuration?

**Comment by asynts** [comment]
> But is it necessary to have a distinction between a secret and a configuration?

In my pull request they are treated equally. This does have the downside that secrets could be exposed if some code dynamically loads configuration in a way that could be manipulated by a end user. Personally, if we write code like that we deserve what we get.

It might be reasonable to use amazons secret manager anyways to rotate secrets, again, I would have to do some research first.

**Comment by asynts** [comment]
> *(myself)* It might be reasonable to use amazons secret manager anyways to rotate secrets, again, I would have to do some research first.

Disregard that, we could do this later by providing a `IConfigurationSource` for AWS's secrets service and use the parameter store for now (which seems easier to setup).

**Comment by misha130** [comment]
> Forget that, we could do this later by providing a IConfigurationSource for AWS's secrets service and use the parameter store for now (that seems easier to setup).

Well point is if you treat them equal then when you use the AWS secret service you only use the AWS secret service. Everything comes back from that and not the configuration parameters

**Comment by asynts** [comment]
> Everything comes back from that and not the configuration parameters.

My idea was to add an **additional** `IConfigurationSource` that provides some options. We could still used the `appsettings.json` file or the parameter store at the same time.

**Comment by misha130** [comment]
2 Configuration Sources working at the same time?
Or somehow telling the configuration source to use sometimes this and sometimes this?

**Comment by asynts** [comment]
There are many configuration sources added by default. You have the user secrets, the `appsettings.json` file, the <code>appsettings.<i>&lt;Environment&gt;</i>.json</code> file and environment variables are used too.

It uses them in the reversed order in which they are added as far as I know.

**Comment by misha130** [comment]
Alright, got it. It tries each until it finds the one.
Hopefully this won't cause a problem with the async in the future since IConfig is always sync and the secrets are async.
But we can adjust that later. Sounds good to me in general

**Comment by asynts** [comment]
> Hopefully this won't cause a problem with the async in the future since IConfig is always sync and the secrets are async.

We don't want to fetch the secret every single time, it would be loaded once and then cached. I do not think that this will be an issue.

**Pull request closed without merging**
